// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance_records.sql

package database

import (
	"context"
	"database/sql"
)

const createRecords = `-- name: CreateRecords :exec
INSERT INTO attendance_records (session_id, student_id)
SELECT ?, e.student_id
FROM enrollments e
WHERE e.course_id = ?
`

type CreateRecordsParams struct {
	SessionID int64
	CourseID  string
}

func (q *Queries) CreateRecords(ctx context.Context, arg CreateRecordsParams) error {
	_, err := q.db.ExecContext(ctx, createRecords, arg.SessionID, arg.CourseID)
	return err
}

const getRecordBySession = `-- name: GetRecordBySession :many
SELECT r.id, r.session_id, r.student_id, r.status, r.check_in_at, r.student_lat, r.student_lng, r.accuracy, r.device_fingerprint , s.first_name, s.last_name, s.student_id
FROM attendance_records r
JOIN students s ON r.student_id = s.id
WHERE r.session_id = ?
`

type GetRecordBySessionRow struct {
	ID                int64
	SessionID         int64
	StudentID         string
	Status            string
	CheckInAt         sql.NullString
	StudentLat        sql.NullFloat64
	StudentLng        sql.NullFloat64
	Accuracy          sql.NullFloat64
	DeviceFingerprint sql.NullString
	FirstName         string
	LastName          string
	StudentID_2       string
}

// get list of students in a session to check their status
func (q *Queries) GetRecordBySession(ctx context.Context, sessionID int64) ([]GetRecordBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecordBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecordBySessionRow
	for rows.Next() {
		var i GetRecordBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StudentID,
			&i.Status,
			&i.CheckInAt,
			&i.StudentLat,
			&i.StudentLng,
			&i.Accuracy,
			&i.DeviceFingerprint,
			&i.FirstName,
			&i.LastName,
			&i.StudentID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAttendanceRecords = `-- name: ResetAttendanceRecords :exec
DELETE FROM attendance_records
`

func (q *Queries) ResetAttendanceRecords(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAttendanceRecords)
	return err
}

const revertCheckin = `-- name: RevertCheckin :one
UPDATE attendance_records
SET status = 'absent', check_in_at = NULL
WHERE student_id = ? AND session_id = ?
RETURNING id, session_id, student_id, status, check_in_at, student_lat, student_lng, accuracy, device_fingerprint
`

type RevertCheckinParams struct {
	StudentID string
	SessionID int64
}

// flip a student's record back to 'absent' ( prof override afrer a flag review)
// clears all checkin metadata so the row looks like the student 'never checkin'
func (q *Queries) RevertCheckin(ctx context.Context, arg RevertCheckinParams) (AttendanceRecord, error) {
	row := q.db.QueryRowContext(ctx, revertCheckin, arg.StudentID, arg.SessionID)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StudentID,
		&i.Status,
		&i.CheckInAt,
		&i.StudentLat,
		&i.StudentLng,
		&i.Accuracy,
		&i.DeviceFingerprint,
	)
	return i, err
}

const studentCheckIn = `-- name: StudentCheckIn :one
UPDATE attendance_records
SET status = 'present' , check_in_at = datetime('now'), student_lat = ?, student_lng = ? , accuracy = ?, device_fingerprint = ?
WHERE session_id = ? AND student_id = ?
RETURNING id, session_id, student_id, status, check_in_at, student_lat, student_lng, accuracy, device_fingerprint
`

type StudentCheckInParams struct {
	StudentLat        sql.NullFloat64
	StudentLng        sql.NullFloat64
	Accuracy          sql.NullFloat64
	DeviceFingerprint sql.NullString
	SessionID         int64
	StudentID         string
}

func (q *Queries) StudentCheckIn(ctx context.Context, arg StudentCheckInParams) (AttendanceRecord, error) {
	row := q.db.QueryRowContext(ctx, studentCheckIn,
		arg.StudentLat,
		arg.StudentLng,
		arg.Accuracy,
		arg.DeviceFingerprint,
		arg.SessionID,
		arg.StudentID,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StudentID,
		&i.Status,
		&i.CheckInAt,
		&i.StudentLat,
		&i.StudentLng,
		&i.Accuracy,
		&i.DeviceFingerprint,
	)
	return i, err
}

const updateCheckIn = `-- name: UpdateCheckIn :one
UPDATE attendance_records
SET status = 'present', check_in_at = datetime('now')
WHERE student_id = ? AND session_id = ?
RETURNING id, session_id, student_id, status, check_in_at, student_lat, student_lng, accuracy, device_fingerprint
`

type UpdateCheckInParams struct {
	StudentID string
	SessionID int64
}

func (q *Queries) UpdateCheckIn(ctx context.Context, arg UpdateCheckInParams) (AttendanceRecord, error) {
	row := q.db.QueryRowContext(ctx, updateCheckIn, arg.StudentID, arg.SessionID)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StudentID,
		&i.Status,
		&i.CheckInAt,
		&i.StudentLat,
		&i.StudentLng,
		&i.Accuracy,
		&i.DeviceFingerprint,
	)
	return i, err
}
