// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance_sessions.sql

package database

import (
	"context"
	"database/sql"
)

const closeSession = `-- name: CloseSession :one
UPDATE attendance_sessions
SET status = 'closed', ended_at = datetime('now')
WHERE id = ?
RETURNING id, course_id, session_date, status, secret_key, classroom_lat, classroom_lng, radius_meters, started_at, ended_at
`

func (q *Queries) CloseSession(ctx context.Context, id int64) (AttendanceSession, error) {
	row := q.db.QueryRowContext(ctx, closeSession, id)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SessionDate,
		&i.Status,
		&i.SecretKey,
		&i.ClassroomLat,
		&i.ClassroomLng,
		&i.RadiusMeters,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO attendance_sessions (
    course_id,
    session_date,
    secret_key,
    classroom_lat,
    classroom_lng,
    radius_meters
)
VALUES (?,?,?,?,?,?)
RETURNING id, course_id, session_date, status, secret_key, classroom_lat, classroom_lng, radius_meters, started_at, ended_at
`

type CreateSessionParams struct {
	CourseID     string
	SessionDate  string
	SecretKey    string
	ClassroomLat sql.NullFloat64
	ClassroomLng sql.NullFloat64
	RadiusMeters sql.NullInt64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AttendanceSession, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.CourseID,
		arg.SessionDate,
		arg.SecretKey,
		arg.ClassroomLat,
		arg.ClassroomLng,
		arg.RadiusMeters,
	)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SessionDate,
		&i.Status,
		&i.SecretKey,
		&i.ClassroomLat,
		&i.ClassroomLng,
		&i.RadiusMeters,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM attendance_sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, course_id, session_date, status, secret_key, classroom_lat, classroom_lng, radius_meters, started_at, ended_at FROM attendance_sessions
WHERE course_id = ? AND status = 'active'
`

// get active session for a course (to check if one already exists)
func (q *Queries) GetActiveSession(ctx context.Context, courseID string) (AttendanceSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveSession, courseID)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SessionDate,
		&i.Status,
		&i.SecretKey,
		&i.ClassroomLat,
		&i.ClassroomLng,
		&i.RadiusMeters,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, course_id, session_date, status, secret_key, classroom_lat, classroom_lng, radius_meters, started_at, ended_at FROM attendance_sessions
WHERE id = ?
`

// get session by ID
func (q *Queries) GetSessionByID(ctx context.Context, id int64) (AttendanceSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SessionDate,
		&i.Status,
		&i.SecretKey,
		&i.ClassroomLat,
		&i.ClassroomLng,
		&i.RadiusMeters,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const reOpenSession = `-- name: ReOpenSession :one
UPDATE attendance_sessions
SET status = 'active', ended_at = NULL
WHERE id = ? 
RETURNING id, course_id, session_date, status, secret_key, classroom_lat, classroom_lng, radius_meters, started_at, ended_at
`

func (q *Queries) ReOpenSession(ctx context.Context, id int64) (AttendanceSession, error) {
	row := q.db.QueryRowContext(ctx, reOpenSession, id)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.SessionDate,
		&i.Status,
		&i.SecretKey,
		&i.ClassroomLat,
		&i.ClassroomLng,
		&i.RadiusMeters,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const resetAttendanceSession = `-- name: ResetAttendanceSession :exec
DELETE FROM attendance_sessions
`

func (q *Queries) ResetAttendanceSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAttendanceSession)
	return err
}
