// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package database

import (
	"context"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (id, course_name, section_date, start_time)
VALUES (?,?,?,?)
RETURNING id, course_name, section_date, start_time, created_at
`

type CreateCourseParams struct {
	ID          string
	CourseName  string
	SectionDate string
	StartTime   string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, createCourse,
		arg.ID,
		arg.CourseName,
		arg.SectionDate,
		arg.StartTime,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CourseName,
		&i.SectionDate,
		&i.StartTime,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllCourse = `-- name: DeleteAllCourse :exec
DELETE FROM courses
`

func (q *Queries) DeleteAllCourse(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCourse)
	return err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses 
WHERE id = ?
`

func (q *Queries) DeleteCourse(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCourse, id)
	return err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, course_name, section_date, start_time, created_at FROM courses WHERE id = ?
`

func (q *Queries) GetCourseByID(ctx context.Context, id string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CourseName,
		&i.SectionDate,
		&i.StartTime,
		&i.CreatedAt,
	)
	return i, err
}

const listAllCourses = `-- name: ListAllCourses :many
SELECT id, course_name, section_date, start_time, created_at FROM courses
`

func (q *Queries) ListAllCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listAllCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CourseName,
			&i.SectionDate,
			&i.StartTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourseName = `-- name: UpdateCourseName :exec
UPDATE courses 
SET course_name = ? WHERE id = ?
`

type UpdateCourseNameParams struct {
	CourseName string
	ID         string
}

func (q *Queries) UpdateCourseName(ctx context.Context, arg UpdateCourseNameParams) error {
	_, err := q.db.ExecContext(ctx, updateCourseName, arg.CourseName, arg.ID)
	return err
}

const updateCourseSection = `-- name: UpdateCourseSection :exec
UPDATE courses 
SET section_date = ? WHERE id = ?
`

type UpdateCourseSectionParams struct {
	SectionDate string
	ID          string
}

func (q *Queries) UpdateCourseSection(ctx context.Context, arg UpdateCourseSectionParams) error {
	_, err := q.db.ExecContext(ctx, updateCourseSection, arg.SectionDate, arg.ID)
	return err
}

const updateCourseStartTime = `-- name: UpdateCourseStartTime :exec
UPDATE courses
SET start_time = ? WHERE id = ?
`

type UpdateCourseStartTimeParams struct {
	StartTime string
	ID        string
}

func (q *Queries) UpdateCourseStartTime(ctx context.Context, arg UpdateCourseStartTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateCourseStartTime, arg.StartTime, arg.ID)
	return err
}
