// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devide_fingerprint.sql

package database

import (
	"context"
	"database/sql"
)

const getFlaggedFingerprints = `-- name: GetFlaggedFingerprints :many
SELECT
    a1.device_fingerprint,
    a1.student_id,
    s.student_id AS school_id,
    s.first_name,
    s.last_name,
    a1.check_in_at
FROM attendance_records a1
JOIN students s ON s.id = a1.student_id
WHERE a1.session_id = ?
    AND a1.device_fingerprint IS NOT NULL
    AND a1.device_fingerprint != ''
    AND EXISTS (
        SELECT 1 FROM attendance_records a2
        WHERE a2.session_id = a1.session_id
            AND a2.device_fingerprint = a1.device_fingerprint
            AND a2.student_id != a1.student_id
    )
ORDER BY a1.device_fingerprint, a1.check_in_at
`

type GetFlaggedFingerprintsRow struct {
	DeviceFingerprint sql.NullString
	StudentID         string
	SchoolID          string
	FirstName         string
	LastName          string
	CheckInAt         sql.NullString
}

// find suspicious identical fingerprint for different accounts.
// returns students whose fingerprint matches at least 1 other student
// in the same session, regardless of current status — so flag history
// stays visible after the prof marks a cheater absent.
func (q *Queries) GetFlaggedFingerprints(ctx context.Context, sessionID int64) ([]GetFlaggedFingerprintsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFlaggedFingerprints, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlaggedFingerprintsRow
	for rows.Next() {
		var i GetFlaggedFingerprintsRow
		if err := rows.Scan(
			&i.DeviceFingerprint,
			&i.StudentID,
			&i.SchoolID,
			&i.FirstName,
			&i.LastName,
			&i.CheckInAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
