// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollments.sql

package database

import (
	"context"
	"database/sql"
)

const getAllStudentsByCourse = `-- name: GetAllStudentsByCourse :many
SELECT s.id, s.student_id, s.email, s.first_name, s.last_name, s.specialty 
FROM students s 
JOIN enrollments e ON s.id = e.student_id
WHERE e.course_id = ?
`

type GetAllStudentsByCourseRow struct {
	ID        string
	StudentID string
	Email     string
	FirstName string
	LastName  string
	Specialty sql.NullString
}

// show list of all students that have registered for a course
func (q *Queries) GetAllStudentsByCourse(ctx context.Context, courseID string) ([]GetAllStudentsByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllStudentsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllStudentsByCourseRow
	for rows.Next() {
		var i GetAllStudentsByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Specialty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrollmentsByStudent = `-- name: GetEnrollmentsByStudent :many
SELECT c.id, c.course_name, c.section_date, c.start_time 
FROM courses c 
JOIN enrollments e ON c.id = e.course_id
WHERE e.student_id = ?
`

type GetEnrollmentsByStudentRow struct {
	ID          string
	CourseName  string
	SectionDate string
	StartTime   string
}

func (q *Queries) GetEnrollmentsByStudent(ctx context.Context, studentID string) ([]GetEnrollmentsByStudentRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnrollmentsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnrollmentsByStudentRow
	for rows.Next() {
		var i GetEnrollmentsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseName,
			&i.SectionDate,
			&i.StartTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newEnrollment = `-- name: NewEnrollment :one
INSERT INTO enrollments (student_id, course_id)
VALUES (?,?)
RETURNING student_id, course_id
`

type NewEnrollmentParams struct {
	StudentID string
	CourseID  string
}

func (q *Queries) NewEnrollment(ctx context.Context, arg NewEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, newEnrollment, arg.StudentID, arg.CourseID)
	var i Enrollment
	err := row.Scan(&i.StudentID, &i.CourseID)
	return i, err
}

const resetEnrollment = `-- name: ResetEnrollment :exec
DELETE FROM enrollments
`

func (q *Queries) ResetEnrollment(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetEnrollment)
	return err
}
