// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type AttendanceRecord struct {
	ID                int64
	SessionID         int64
	StudentID         string
	Status            string
	CheckInAt         sql.NullString
	StudentLat        sql.NullFloat64
	StudentLng        sql.NullFloat64
	Accuracy          sql.NullFloat64
	DeviceFingerprint sql.NullString
}

type AttendanceSession struct {
	ID           int64
	CourseID     string
	SessionDate  string
	Status       string
	SecretKey    string
	ClassroomLat sql.NullFloat64
	ClassroomLng sql.NullFloat64
	RadiusMeters sql.NullInt64
	StartedAt    string
	EndedAt      sql.NullString
}

type Course struct {
	ID          string
	CourseName  string
	SectionDate string
	StartTime   string
	CreatedAt   string
}

type Enrollment struct {
	StudentID string
	CourseID  string
}

type Specialty struct {
	ID        int64
	Name      string
	CreatedAt string
}

type Student struct {
	ID                    string
	StudentID             string
	Email                 string
	PasswordHash          sql.NullString
	FirstName             string
	LastName              string
	Verified              int64
	Specialty             sql.NullString
	CreatedAt             string
	UpdatedAt             string
	RegisteredFingerprint sql.NullString
}
