// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Course struct {
	ID          string
	CourseName  string
	SectionDate string
	StartTime   string
	CreatedAt   string
}

type Enrollment struct {
	StudentID string
	CourseID  string
}

type Student struct {
	ID           string
	StudentID    string
	Email        string
	PasswordHash sql.NullString
	FirstName    string
	LastName     string
	Verified     int64
	Specialty    sql.NullString
	CreatedAt    string
	UpdatedAt    string
}
