// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package database

import (
	"context"
	"database/sql"
)

const getAttendanceByDate = `-- name: GetAttendanceByDate :many
SELECT
    sess.session_date,
    c.course_name,
    c.start_time,
    s.student_id,
    s.first_name,
    s.last_name,
    r.status,
    r.check_in_at
FROM attendance_records r 
JOIN students s ON r.student_id = s.id 
JOIN attendance_sessions sess ON r.session_id = sess.id 
JOIN courses c ON sess.course_id = c.id 
WHERE sess.session_date = ?
ORDER BY c.start_time, s.last_name, s.first_name
`

type GetAttendanceByDateRow struct {
	SessionDate string
	CourseName  string
	StartTime   string
	StudentID   string
	FirstName   string
	LastName    string
	Status      string
	CheckInAt   sql.NullString
}

// daily report: all records for sessions on a specific date
func (q *Queries) GetAttendanceByDate(ctx context.Context, sessionDate string) ([]GetAttendanceByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getAttendanceByDate, sessionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceByDateRow
	for rows.Next() {
		var i GetAttendanceByDateRow
		if err := rows.Scan(
			&i.SessionDate,
			&i.CourseName,
			&i.StartTime,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.CheckInAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendanceSummaryByCourse = `-- name: GetAttendanceSummaryByCourse :many
SELECT 
    s.student_id,
    s.first_name,
    s.last_name,
    s.specialty,
    COUNT(CASE WHEN r.status='present' THEN 1 END) AS total_present,
    COUNT(r.id) AS total_sessions,
    ROUND(COUNT(CASE WHEN r.status='present' THEN 1 END)*100.0/COUNT(r.id), 1) AS average
FROM students s 
JOIN attendance_records r ON s.id = r.student_id
JOIN attendance_sessions sess ON r.session_id = sess.id 
WHERE sess.course_id = ?
GROUP BY s.id 
ORDER BY s.last_name, s.first_name
`

type GetAttendanceSummaryByCourseRow struct {
	StudentID     string
	FirstName     string
	LastName      string
	Specialty     sql.NullString
	TotalPresent  int64
	TotalSessions int64
	Average       float64
}

// semester report: count attendance per student for a course
func (q *Queries) GetAttendanceSummaryByCourse(ctx context.Context, courseID string) ([]GetAttendanceSummaryByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getAttendanceSummaryByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceSummaryByCourseRow
	for rows.Next() {
		var i GetAttendanceSummaryByCourseRow
		if err := rows.Scan(
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Specialty,
			&i.TotalPresent,
			&i.TotalSessions,
			&i.Average,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendanceSummaryByCourseInDateRange = `-- name: GetAttendanceSummaryByCourseInDateRange :many
SELECT 
    s.student_id,
    s.first_name,
    s.last_name,
    s.specialty,
    COUNT(CASE WHEN r.status='present' THEN 1 END) AS total_present,
    COUNT(r.id) AS total_sessions,
    ROUND(COUNT(CASE WHEN r.status='present' THEN 1 END)*100.0/COUNT(r.id), 1) AS average
FROM students s 
JOIN attendance_records r ON r.student_id = s.id 
JOIN attendance_sessions sess ON r.session_id = sess.id 
WHERE sess.course_id = ? AND sess.session_date >= ? AND sess.session_date <= ?
GROUP BY s.id 
ORDER BY s.last_name, s.first_name
`

type GetAttendanceSummaryByCourseInDateRangeParams struct {
	CourseID      string
	SessionDate   string
	SessionDate_2 string
}

type GetAttendanceSummaryByCourseInDateRangeRow struct {
	StudentID     string
	FirstName     string
	LastName      string
	Specialty     sql.NullString
	TotalPresent  int64
	TotalSessions int64
	Average       float64
}

// get attendance records by date range
func (q *Queries) GetAttendanceSummaryByCourseInDateRange(ctx context.Context, arg GetAttendanceSummaryByCourseInDateRangeParams) ([]GetAttendanceSummaryByCourseInDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getAttendanceSummaryByCourseInDateRange, arg.CourseID, arg.SessionDate, arg.SessionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceSummaryByCourseInDateRangeRow
	for rows.Next() {
		var i GetAttendanceSummaryByCourseInDateRangeRow
		if err := rows.Scan(
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Specialty,
			&i.TotalPresent,
			&i.TotalSessions,
			&i.Average,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
