// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: specialties.sql

package database

import (
	"context"
)

const createSpecialty = `-- name: CreateSpecialty :one
INSERT INTO specialties (name)
VALUES (?)
RETURNING id, name, created_at
`

func (q *Queries) CreateSpecialty(ctx context.Context, name string) (Specialty, error) {
	row := q.db.QueryRowContext(ctx, createSpecialty, name)
	var i Specialty
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteSpecialty = `-- name: DeleteSpecialty :exec
DELETE FROM specialties WHERE id = ?
`

// delete a specialty from the list
func (q *Queries) DeleteSpecialty(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSpecialty, id)
	return err
}

const listAllSpecialties = `-- name: ListAllSpecialties :many
SELECT id, name, created_at FROM specialties
ORDER BY name
`

func (q *Queries) ListAllSpecialties(ctx context.Context) ([]Specialty, error) {
	rows, err := q.db.QueryContext(ctx, listAllSpecialties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialty
	for rows.Next() {
		var i Specialty
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSpecialties = `-- name: ResetSpecialties :exec
DELETE FROM specialties
`

// reset the specialties table
func (q *Queries) ResetSpecialties(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSpecialties)
	return err
}
