// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package database

import (
	"context"
	"database/sql"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (id, student_id, email, password_hash, first_name, last_name, verified, specialty, registered_fingerprint)
VALUES (?,?,?,?,?,?, 1 ,?, ?)
RETURNING id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at, registered_fingerprint
`

type CreateStudentParams struct {
	ID                    string
	StudentID             string
	Email                 string
	PasswordHash          sql.NullString
	FirstName             string
	LastName              string
	Specialty             sql.NullString
	RegisteredFingerprint sql.NullString
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, createStudent,
		arg.ID,
		arg.StudentID,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Specialty,
		arg.RegisteredFingerprint,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegisteredFingerprint,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM students
WHERE id = ?
`

func (q *Queries) DeleteStudent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteStudent, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at, registered_fingerprint FROM students
WHERE id = ?
`

func (q *Queries) GetByID(ctx context.Context, id string) (Student, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegisteredFingerprint,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one

SELECT id, student_id, first_name, last_name, specialty, email
FROM students WHERE id = ?
`

type GetProfileByIDRow struct {
	ID        string
	StudentID string
	FirstName string
	LastName  string
	Specialty sql.NullString
	Email     string
}

// student editing profile feature
// Search for one student's profile by the UUID
func (q *Queries) GetProfileByID(ctx context.Context, id string) (GetProfileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByID, id)
	var i GetProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Specialty,
		&i.Email,
	)
	return i, err
}

const getStudentByEmail = `-- name: GetStudentByEmail :one
SELECT id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at, registered_fingerprint FROM students
WHERE email = ?
`

func (q *Queries) GetStudentByEmail(ctx context.Context, email string) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByEmail, email)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegisteredFingerprint,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at, registered_fingerprint FROM students
WHERE student_id = ?
`

func (q *Queries) GetStudentByID(ctx context.Context, studentID string) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByID, studentID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegisteredFingerprint,
	)
	return i, err
}

const listAllStudents = `-- name: ListAllStudents :many
SELECT id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at, registered_fingerprint FROM students
`

func (q *Queries) ListAllStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listAllStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Verified,
			&i.Specialty,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RegisteredFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetStudents = `-- name: ResetStudents :exec
DELETE FROM students
`

func (q *Queries) ResetStudents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetStudents)
	return err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE students
SET password_hash = ?, updated_at = datetime('now'), verified = 1
WHERE student_id = ?
RETURNING id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at, registered_fingerprint
`

type UpdatePasswordParams struct {
	PasswordHash sql.NullString
	StudentID    string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updatePassword, arg.PasswordHash, arg.StudentID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegisteredFingerprint,
	)
	return i, err
}

const updateStudentEmail = `-- name: UpdateStudentEmail :one
UPDATE students
SET email = ?, updated_at = datetime('now')
WHERE student_id = ?
RETURNING id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at, registered_fingerprint
`

type UpdateStudentEmailParams struct {
	Email     string
	StudentID string
}

func (q *Queries) UpdateStudentEmail(ctx context.Context, arg UpdateStudentEmailParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updateStudentEmail, arg.Email, arg.StudentID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegisteredFingerprint,
	)
	return i, err
}

const updateStudentEmailByID = `-- name: UpdateStudentEmailByID :one
UPDATE students 
SET email = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at, registered_fingerprint
`

type UpdateStudentEmailByIDParams struct {
	Email string
	ID    string
}

func (q *Queries) UpdateStudentEmailByID(ctx context.Context, arg UpdateStudentEmailByIDParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updateStudentEmailByID, arg.Email, arg.ID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegisteredFingerprint,
	)
	return i, err
}

const updateStudentName = `-- name: UpdateStudentName :one
UPDATE students 
SET first_name = ?, last_name = ? , updated_at = datetime('now')
WHERE id = ?
RETURNING id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at, registered_fingerprint
`

type UpdateStudentNameParams struct {
	FirstName string
	LastName  string
	ID        string
}

func (q *Queries) UpdateStudentName(ctx context.Context, arg UpdateStudentNameParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updateStudentName, arg.FirstName, arg.LastName, arg.ID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegisteredFingerprint,
	)
	return i, err
}

const updateStudentSchoolID = `-- name: UpdateStudentSchoolID :one
UPDATE students 
SET student_id = ? , updated_at = datetime('now')
WHERE id = ?
RETURNING id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at, registered_fingerprint
`

type UpdateStudentSchoolIDParams struct {
	StudentID string
	ID        string
}

func (q *Queries) UpdateStudentSchoolID(ctx context.Context, arg UpdateStudentSchoolIDParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updateStudentSchoolID, arg.StudentID, arg.ID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegisteredFingerprint,
	)
	return i, err
}
