// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package database

import (
	"context"
	"database/sql"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (id, student_id, email, first_name, last_name, specialty)
VALUES (?,?,?,?,?,?)
RETURNING id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at
`

type CreateStudentParams struct {
	ID        string
	StudentID string
	Email     string
	FirstName string
	LastName  string
	Specialty sql.NullString
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, createStudent,
		arg.ID,
		arg.StudentID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Specialty,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM students
WHERE id = ?
`

func (q *Queries) DeleteStudent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteStudent, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at FROM students
WHERE id = ?
`

func (q *Queries) GetByID(ctx context.Context, id string) (Student, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByEmail = `-- name: GetStudentByEmail :one
SELECT id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at FROM students
WHERE email = ?
`

func (q *Queries) GetStudentByEmail(ctx context.Context, email string) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByEmail, email)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at FROM students
WHERE student_id = ?
`

func (q *Queries) GetStudentByID(ctx context.Context, studentID string) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByID, studentID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllStudents = `-- name: ListAllStudents :many
SELECT id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at FROM students
`

func (q *Queries) ListAllStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listAllStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Verified,
			&i.Specialty,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE students
SET password_hash = ?, updated_at = datetime('now'), verified = 1
WHERE student_id = ?
RETURNING id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at
`

type UpdatePasswordParams struct {
	PasswordHash sql.NullString
	StudentID    string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updatePassword, arg.PasswordHash, arg.StudentID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStudentEmail = `-- name: UpdateStudentEmail :one
UPDATE students
SET email = ?, updated_at = datetime('now')
WHERE student_id = ?
RETURNING id, student_id, email, password_hash, first_name, last_name, verified, specialty, created_at, updated_at
`

type UpdateStudentEmailParams struct {
	Email     string
	StudentID string
}

func (q *Queries) UpdateStudentEmail(ctx context.Context, arg UpdateStudentEmailParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updateStudentEmail, arg.Email, arg.StudentID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Verified,
		&i.Specialty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
